version: "3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
    image: mongo:3.6.7-jessie
    ports:
      - "27017:27017"
